// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace blazelogBase.Store.Models;

[Table("CoreUser")]
public partial class CoreUser
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string UserId { get; set; }

    [Required]
    [StringLength(100)]
    public string UserName { get; set; }

    [StringLength(200)]
    public string Person { get; set; }

    [Required]
    public string EncPassword { get; set; }

    public bool Disabled { get; set; }

    public bool IsAdmin { get; set; }

    public bool IsReset { get; set; }

    [Column("loginedAt", TypeName = "datetime")]
    public DateTime? LoginedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [Required]
    [Column("updatedBy")]
    [StringLength(100)]
    public string UpdatedBy { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("level")]
    public int Level { get; set; }

    [Column("post")]
    [StringLength(50)]
    public string Post { get; set; }

    [Column("tel")]
    [StringLength(50)]
    public string Tel { get; set; }

    [StringLength(50)]
    public string Division { get; set; }

    [StringLength(50)]
    public string AdminScope { get; set; }

    [Column("email")]
    [StringLength(250)]
    public string Email { get; set; }
}