// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace blazelogBase.Store.Models;

[Table("CoreSetting")]
public partial class CoreSetting
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string SettingId { get; set; }

    [StringLength(1000)]
    public string SettingValue { get; set; }

    public bool CanEdit { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [Column("updatedBy")]
    [StringLength(50)]
    public string UpdatedBy { get; set; }
}